//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_Stock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accesspoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accesspoint()
        {
            this.historial_access = new HashSet<historial_access>();
            this.historial_access1 = new HashSet<historial_access>();
        }
    
        public int id_accesspoint { get; set; }
        public int codigo { get; set; }
        public string nombre { get; set; }
        public string estatus { get; set; }
        public string asignado { get; set; }
        public int num_inventario { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string num_serie { get; set; }
        public int mac_address { get; set; }
        public string tipo_seguridad { get; set; }
        public string observaciones { get; set; }
        public int id_categoria { get; set; }
        public string url_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historial_access> historial_access { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historial_access> historial_access1 { get; set; }
    }
}
