//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_Stock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class almacenamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public almacenamiento()
        {
            this.historial_almacenamiento = new HashSet<historial_almacenamiento>();
            this.historial_almacenamiento1 = new HashSet<historial_almacenamiento>();
        }
    
        public int id_almacenamiento { get; set; }
        public string nombre_almacen { get; set; }
        public int stock_almacen { get; set; }
        public string tipo { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string num_serie { get; set; }
        public int capacidad { get; set; }
        public string conectividad { get; set; }
        public int id_categoria { get; set; }
        public string url_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historial_almacenamiento> historial_almacenamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historial_almacenamiento> historial_almacenamiento1 { get; set; }
    }
}
