//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_Stock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class disprespaldo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public disprespaldo()
        {
            this.historial_disprespaldo = new HashSet<historial_disprespaldo>();
            this.historial_disprespaldo1 = new HashSet<historial_disprespaldo>();
        }
    
        public int id_disprespaldo { get; set; }
        public string nombre_resp { get; set; }
        public int num_inventario { get; set; }
        public string tipo { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string num_serie { get; set; }
        public string herramienta_resp { get; set; }
        public string tipo_medio { get; set; }
        public string informacion { get; set; }
        public string periodicidad { get; set; }
        public string lugar_resguardo { get; set; }
        public int id_categoria { get; set; }
        public string url_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historial_disprespaldo> historial_disprespaldo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historial_disprespaldo> historial_disprespaldo1 { get; set; }
    }
}
