//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_Stock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_conmutador
    {
        public int id_historial { get; set; }
        public int id_conmutador { get; set; }
        public int user_id { get; set; }
        public System.DateTime fecha { get; set; }
        public string nota { get; set; }
        public string referencia { get; set; }
        public int cantidad { get; set; }
    
        public virtual conmutador conmutador { get; set; }
        public virtual conmutador conmutador1 { get; set; }
        public virtual users users { get; set; }
    }
}
