//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_Stock.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class simple_stockEntities : DbContext
    {
        public simple_stockEntities()
            : base("name=simple_stockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accesspoint> accesspoint { get; set; }
        public virtual DbSet<almacenamiento> almacenamiento { get; set; }
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<centrodedatos> centrodedatos { get; set; }
        public virtual DbSet<conmutador> conmutador { get; set; }
        public virtual DbSet<disprespaldo> disprespaldo { get; set; }
        public virtual DbSet<enlaces> enlaces { get; set; }
        public virtual DbSet<historial> historial { get; set; }
        public virtual DbSet<historial_access> historial_access { get; set; }
        public virtual DbSet<historial_almacenamiento> historial_almacenamiento { get; set; }
        public virtual DbSet<historial_centro> historial_centro { get; set; }
        public virtual DbSet<historial_conmutador> historial_conmutador { get; set; }
        public virtual DbSet<historial_disprespaldo> historial_disprespaldo { get; set; }
        public virtual DbSet<historial_enlace> historial_enlace { get; set; }
        public virtual DbSet<historial_servidor> historial_servidor { get; set; }
        public virtual DbSet<historial_switrout> historial_switrout { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<servidores> servidores { get; set; }
        public virtual DbSet<switrout> switrout { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
